### ISSUE TITLE
Can not run reinvent 3.0 successfully on RTX3090

### ISSUE THREAD

**Issue by yrq3027** [MolecularAI/Reinvent#40]
Excuse me Sir，
Followed errors come when I running the notebook. I also tried pytorch 1.10.1. Could you give some advice to solve this problem?
Thank you!

/home/user/anaconda3/envs/reinvent.v3.0/lib/python3.7/site-packages/torch/cuda/__init__.py:143: UserWarning: 
GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

**Comment by xuzhang5788** [comment]
@yrq3027 
I met this problem before. I updated pytorch to the latest version and it works.

**Comment by yrq3027** [comment]
> @yrq3027 I met this problem before. I updated pytorch to the latest version and it works.

Thank you. It worked after I installing torch again. May caused by cuda version.
